version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  express:
    build: ./server
    container_name: express-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge