services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  express:
    build: ./server
    container_name: express-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/mydatabase"
    networks:
      - backend

  react:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - express
    networks:
      - backend

volumes:
  mongo-data:


networks:
  backend:
    driver: bridge
